# -*- coding: utf-8 -*-
"""LMWNMysteriousCode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eui7ErAvgko6zO2rk2Qt0mZOZVlxA5XO
"""

import base64
target = "aWFuZ25vVzpOQU06RU5JTDp0YTpzdTpuaW9K"
data = base64.b64decode(target).decode("utf-8")
data_rev = data [::-1] 
print(data_rev)

